### ISSUE TITLE
error 010240 create constant raster connectivity index tool

### ISSUE THREAD

**Issue by Pauli999** [HydrogeomorphologyTools/Connectivity-Index-ArcGIS-toolbox#1]
I have a problem with saving the constant raster when I run the connectivity index tool (see print screen please). The save location is in my app data and I checked there is no file with the same name. Does somebody know how to solve this issue or set another save location? Thanks in advance

![print screen](https://user-images.githubusercontent.com/28714466/27484113-63cd374e-57fe-11e7-8a66-6d82fe14e294.png)

**Comment by HydrogeomorphologyTools** [comment]
Hello, it looks like a folder path settings error in the tool's environments, you probably need to change ArcMap environments cause those settings are not managed by the tool (like default workspace, processing extent etc...)
By the way, we suggest to use SedInConnect tool for IC computation, you can download the stand-alone implementation at https://github.com/HydrogeomorphologyTools/SedInConnect_2.3/releases
In case you prefer, for further detail you can contact directly me at crema.stefano@gmail.com, we can try to fix the issue step by step if you're not familiar with ArcMap environment settings
