### ISSUE TITLE
Red cross on a tool 

### ISSUE THREAD

**Issue by jacalcantara** [HydrogeomorphologyTools/Connectivity-Index-ArcGIS-toolbox#2]
Please, how can a fix that problema about a red cross on a tool? That say that I am unable to execute the selected tool.

**Comment by HydrogeomorphologyTools** [comment]
Hi, clues are rather generic but in most of the cases it's a bug related to one of the TauDEM tools toolboxes, I assume you've already installed TAUDEM (https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe) . If this is the case, a couple of solutions can be taken in consideration:
- checking the path to the TauDEM tool is correct
- checking whether one of the TauDEM tools is creating an output with a default name (already used by another instance of the same tool), and modifying it according to the variable names you can infer from the model builder.

I would suggest also to take in consideration SedInConnect (https://github.com/HydrogeomorphologyTools/SedInConnect_2.3/releases/tag/SedInConnect_2.3) which does basically the same analysis but is pretty straightforward and does not require any GIS software. TauDEM needs to be installed also in this case but for the rest, it's very simple and it requires only a DTM (GeoTIFF uncompressed) in input. If you want to carry out IC analysis at tha catchment scale and you have a high resolution DTM in fact, you can select it also to compute surface roughness and use it as weighting factor.
In case you need to set a target (optional), this must be a Polygonal shapefile, like a small buffer of the river network.
SedInConnect reference paper can be found here: https://www.sciencedirect.com/science/article/pii/S0098300416308275

For more information on TauDEM errors, you can have a look also at the troubleshooting of TauDEM tools: http://hydrology.usu.edu/taudem/taudem5/troubleshooting.html 

In case things do not get resolved you can contact me via skype, mi id is: **_cremastefano_**
